/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LoginGoogleRequest {
  credential: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}
