/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AddTodoRequest {
  category: string;
  createdAt: Date;
  name: string;
}

export interface TodoCategoryListRequest {
  limit?: number;
  offset?: number;
}

export interface TodoListRequest {
  createdAt: Date;
}
